ToDoApplication/Models/ApplicationDbContext.cs
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ToDoApplication.Models
{
    public class ApplicationDbContext : DbContext
    {
        public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options) : base(options) { }

        public DbSet<Todo> Todos { get; set; }
    }
}

ToDoApplication/Models/ErrorViewModel.cs
using System;

namespace ToDoApplication.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ToDoApplication/Models/Todo.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace ToDoApplication.Models
{
    public class Todo
    {
        [Key]
        public int Id { get; set; }

        [Required]
        public string Content { get; set; }
    }
}

ToDoApplication/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using ToDoApplication.Models;

namespace ToDoApplication.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ToDoApplication/Controllers/TodosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ToDoApplication.Models;

namespace ToDoApplication.Controllers
{
    public class TodosController : Controller
    {
        private readonly ApplicationDbContext _db;

        [BindProperty]
        public Todo Todo { get; set; }

        public TodosController(ApplicationDbContext db)
        {
            _db = db;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _db.Todos.ToListAsync());
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateTodo(Todo todo)
        {
            if (ModelState.IsValid)
            {
                await _db.Todos.AddAsync(todo);
                await _db.SaveChangesAsync();
            }
            return RedirectToAction("Index");
        }

        // Delete Todo
        [HttpPost]
        public async Task<IActionResult> Delete(int todoId)
        {


            var todoFromDb = await _db.Todos.FirstOrDefaultAsync(u => u.Id == todoId);
            if(todoFromDb == null) { return NotFound(); }
            
                _db.Todos.Remove(todoFromDb);
                await _db.SaveChangesAsync();
            return RedirectToAction("Index");
        }


    }
}

ToDoApplication/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ToDoApplication/Views/Shared/_Layout.cshtml
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ToDoApplication</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/todo.css" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ToDoApplication</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Todos" asp-action="Index">Todos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - ToDoApplication - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

ToDoApplication/Views/Todos/Create.cshtml
@model ToDoApplication.Models.Todo



<div class="text-danger" asp-validation-summary="ModelOnly"></div>
<h1 class="text-center">Create Todo</h1>
<br />



<form asp-action="CreateTodo">
    <div class="form-group" id="single_todo_section">
        <label asp-for="Content" class="control-label"></label>
        <input asp-for="Content" class="form-control todo_input" />
    </div>
    <br />
    <div class="validation_message">
        <span asp-validation-for="Content" class="text-danger"></span>
    </div>




    <br />
    <div class="form-group button_area">

        <button type="submit" class="btn btn-primary">
            Add Todo
        </button>
    </div>
</form>
@section Scripts{
    <partial name="_ValidationScriptsPartial" />
}

ToDoApplication/Views/Todos/Index.cshtml
@model IEnumerable<ToDoApplication.Models.Todo>


<h1 class="text-center">Todos</h1>


<div id="all_todos">
    @foreach (var item in Model)
    {
        <div id="single_todo">
            <p class="m-0 p-0" id="todo_content">@Html.DisplayFor(modelItem => item.Content)</p>
            <form  asp-action="Delete" 
               asp-controller="Todos"
               asp-route-todoId="@item.Id"
                  method="post"
                  > 
                <button type="submit" id="delete_button">
                    <svg id="delete_todo_icon" width="1.3em" height="1.3em" viewBox="0 0 16 16" class="bi bi-trash" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                        <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z" />
                        <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4L4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z" />
                    </svg>
                </button>
            </form>
        </div>

    }
    <div id="add_todo_button_section">
        <form asp-area=""
              id="add_button"
              class="text-white"
              asp-controller="Todos"
              asp-action="Create">

            <button type="submit" class="btn btn-primary">

                Add Todo

            </button>
        </form>

    </div>
</div>